### PR TITLE
Various Cache strategies

### PR DESCRIPTION
**Pull request by lukaszwisniewski88**
Just a draft PR introducing possibility to have multiple ways of caching.

### CODE REVIEW

**Comment by frederikhors** [comment]
Really amazing!

**Comment by jycouet** [comment]
@all-contributors please add @lukaszwisniewski88  for code
It's really nice.

I'll have a look right now

**Comment by jycouet** [comment]
Very nice @lukaszwisniewski88 , thx again 🥳

In LocalStorage Indexes are not managed. Was it intended? 
Like this, remove will NEED all variables to be removed, so it will not be the same behavior than InMemory. 

It's not a big deal to add it. Do you want to do it? or?
Il would be nice to have tests as well. Do you want to do it? or?

I can continue, just, I want to avoid that we work both on the same thing ^^

Thx again for your first PR🙏
Let's go to the sky 🥳

**Comment by lukaszwisniewski88** [comment]
Sure thing. I will improve it further, for now it was supposed to be an example implementation.

I will look at it and finish implementing all features and test.

I'll be back with another commit to this PR.

**Comment by jycouet** [comment]
> Sure thing. I will improve it further, for now it was supposed to be an example implementation.
> 
> I will look at it and finish implementing all features and test.
> 
> I'll be back with another commit to this PR.

Awesome,
You should grad the small tweaks that I pushed so that we are aligned.

It's already amazing 👍👍👍.

Can't want to see it 😎.

I'll do IndexDB right after this I think 💪

**Comment by lukaszwisniewski88** [comment]
I'm back with new commits, 

Indexing works like planned. For test i needed to add jsdom enviroment, it has built in mocks for testing involved browser APIs

**Comment by jycouet** [comment]
Looks great @lukaszwisniewski88 🚀
Thx a lot for your contribution 🙏

I'll have a look later 👍

**Comment by jycouet** [comment]
https://github.com/jycouet/kitql/issues/38

**Pull request merged**
