### PR TITLE
:sparkles: IMPROVE: Add keyed queries

### LINKED ISSUE #150: Using prefetch to a page with the same store but different variables causes the page to change immediately
I'm not sure whether this is something to be fixed or worked around, or if there's already a way to handle it that I can't find. I'm at least curious how others have handled this issue.

When you put `sveltekit:prefetch` on an anchor that goes to a page using the same store but different variables, the page's content updates as soon as the prefetched page's data loads.

For instance, imagine you have a `KQL_PlaceById` store which loads for a given place's detail page. If one detail page links to another with `sveltekit:prefetch` on the anchor, when a user hovers over the link the `KQL_PlaceById` store loads with that prefetched place's data. Since the current page is relying on that store for display, it updates immediately, whether the user clicks the prefetched link or not.

I'm thinking I'll get around this by creating a store that holds an object mapping query variables to PlaceById query results with those variables. I wonder whether it would be good to have a similar solution built in, or if there's some way to handle this that I am missing. Thanks!

### PR DESCRIPTION
**Pull request by scottBowles**
Resolves #150 

This PR should not change any existing API, but adds a `.forKey()` method to query stores, which creates or retrieves (if already created) a KitQL store for the given key.

Please do test, and any advice here is also appreciated: I haven't had success `yarn install`ing from my fork so my own testing has involved making changes in my fork, running `build`, then moving the appropriate .dist files to the node_modules of a repo with a frontend and queries to codegen. Not ideal!

### CODE REVIEW

**Comment by jycouet** [comment]
Thx for your pr @scottBowles i'll look into it next week 👍

**Comment by jycouet** [comment]
My original idea was to have only 1 store per Query and go to the cache to fill the store with the right data.
So, if you go from variable A to B to A you will not requery A as you have it already in the cache.

Now, if you have a store per key (variables) it's changing a bit the way things are done. _(It's giving good hint, thx!)_
I would like to tackle this in the new version that we will have in houdini (see https://github.com/jycouet/kitql/discussions/156) where we have way more tests & integration tests.

`prefetch` is part of our roadmap.

**Comment by scottBowles** [comment]
Fair enough. I didn't realize the Houdini integration was as far along as it is! I'll have to give everything over there a good read and start my transition. Thanks as always for all your work!

**Comment by jycouet** [comment]
@scottBowles could you add a route like `/packages/client/src/routes/forkey.svelte`
To demo the usage?

I wanted to have a look but was not able to make it working.
Thx

**Comment by scottBowles** [comment]
There you go!

`/forKey` and `/forKey/{code}` should now hold a pared down version of the continents and countries pages that uses the `forKey` method in the code pages and `sveltekit:prefetch` on the links to them from the `/forKey` page.

For what it's worth, I think each store still accesses the cache in the same way as before and without duplication, since all of the keyed stores have the same `operationName` as the original. If my read is correct, regardless of whether you use the original store or a keyed store, it will use the cache with the same operationName and variables, so the cache layer remains independent and the same cache is used and updated by both original and derivative forKey stores without duplication.

Also, the original store and api remain untouched. Any user can still use the store in its current form and just never call the `.forKey()` method, and everything continues as before.

**Pull request closed without merging**
