### PR TITLE
Update `@kitql/handles` with new features and tests

### PR DESCRIPTION
**Pull request by fnimick**
- add new handles `handleCors`, `handleCsrf`, and utility `createCorsWrapper`
- add integration tests for all functionality

### CODE REVIEW

**Comment by fnimick** [comment]
@jycouet important note - I'm not sure how to run the new `test:e2e` in handles script in CI.

**Comment by jycouet** [comment]
@all-contributors please add @fnimick for code

**Comment by jycouet** [comment]
It's actually already good in `nx cloud`
image

Can you see results too or it's behind a login? 🫣

**Comment by fnimick** [comment]
> Can you see results too or it's behind a login? 🫣

I can see it! I didn't realize there was separate CI configured, I was checking the github actions to see if it would run the new tests I added in addition to the other integration tests and realized that it wouldn't.

**Pull request merged**
